// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://houhjguqdfolfqnzbkrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdWhqZ3VxZGZvbGZxbnpia3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjkwMjYsImV4cCI6MjA1Njk0NTAyNn0.P3Pis60wqIGniZftExxYOL6xBQ8JHKTQdHlZ0AsdkD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);